from __future__ import annotations

from typing import Any, Protocol


class RepositoryPort(Protocol):
    def insert(self, table: str, record: dict[str, Any]) -> None: ...

    def get(self, table: str, record_id: str) -> dict[str, Any] | None: ...

    def update(self, table: str, record_id: str, values: dict[str, Any]) -> None: ...

    def list(self, table: str, *, limit: int = 100) -> list[dict[str, Any]]: ...

    def add_audit_event(self, event: dict[str, Any]) -> None: ...

    def list_audit_events(self, *, limit: int = 100) -> list[dict[str, Any]]: ...

    def get_skill_head(self, skill_name: str) -> dict[str, Any] | None: ...

    def finalize_promotion(self, intent_id: str, version: dict[str, Any]) -> None: ...


class JudgePort(Protocol):
    name: str

    def evaluate(self, content: str, proposed_rule: str) -> dict[str, bool]: ...

